print("Numeros de prueba","2 y 4")
print("La suma es: ", 2+4)
print("La resta es: ", 2-4)
print("La multiplicacion es: ", 2*4)
print("2 elevado a la 4 es: ", 2**4)
print("La division es: ", 2/4)
print("La division entera es: ", 2//4)
print ("El residuo es: ", 2%4)

print("\n Operadores logicos")
print("2 y 4 son iguales: ", 2==4)
print("2 y 4 son diferentes: ", 2!=4)
print("2 es mayor que 4: ", 2>4)
print("2 es menor que 4: ", 2<4)
print("2 es mayor o igual que 4: ", 2>=4)
print("2 es menor o igual que 4: ", 2<=4)

print ("Hola " + str(2) + str(4) )

print (type("24"))
print (type (24))
print (type(float(24)))
